name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.3.1f1

    steps:
      - uses: actions/checkout@v2

      # - uses: testspace-com/setup-testspace@v1
        # with:
          # domain: ${{github.repository_owner}}

      - name: Cache
        uses: actions/cache@v2.1.2
        with:
          path: Library
          key: Library-${{ matrix.unityVersion }}

      - name: Run tests
        id: tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with: 
          unityVersion: ${{ matrix.unityVersion }}
          customParameters: -enableCodeCoverage
            -coverageResultsPath "artifacts/CodeCoverage/"
            -coverageOptions assemblyFilters:+Responsible,+Responsible.Editor
            -nographics
            -disable-assembly-updater
      
      # - name: Push to testspace
        # if: ${{ always() }}
        # run: testspace
          # [${{ matrix.unityVersion }}]artifacts/editmode-results.xml
          # [${{ matrix.unityVersion }}]artifacts/playmode-results.xml

      - name: Push to codecov.io
        uses: codecov/codecov-action@v1
        with:
          files: |
            artifacts/CodeCoverage/workspace-opencov/EditMode/TestCoverageResults_0000.xml,
            artifacts/CodeCoverage/workspace-opencov/PlayMode/TestCoverageResults_0000.xml
          fail_ci_if_error: true
          verbose: true

      - name: Archive test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2.2.0 
        with:
          name: Test Results ${{ matrix.unityVersion }}
          path: artifacts

  # markdown:
    # runs-on: ubuntu-latest

    # steps:
      # - uses: actions/checkout@v2
      # - uses: gaurav-nelson/github-action-markdown-link-check@v1

  inspectcode:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      
      - name: Cache Library
        uses: actions/cache@v2.1.2
        with:
          path: Library
          key: Library-resharper

      - name: Run ReSharper in Unity
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with: 
          customImage: thesbergen/unityci-resharper
          targetPlatform: StandaloneLinux64
          buildMethod: Responsible.EditorSetup.ContinuousIntegration.InspectCode
          customParameters: -disable-assembly-updater

      - name: Archive ReSharper run
        if: ${{ always() }}
        uses: actions/upload-artifact@v2.2.0 
        with:
          name: ReSharper
          path: |
            resharper/inspect.xml
            resharper/stdout.txt
            resharper/stderr.txt

      - name: ReSharper XML -> GitHub output
        if: ${{ always() }}
        uses: glassechidna/resharper-action@v1
        with:
          report: resharper/inspect.xml