name: Unity Test Runner

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

on: [pull_request]

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.3.1f1
        testMode:
          - playmode
          - editmode
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: false # will be true eventually
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restory-keys: |
            Library-
      - name: Tests
        uses: game-ci/unity-test-runner@v2
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          checkName: ${{ matrix.testMode }} Test Results